#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# ──────────────────────────────────────────────────────────────────────────
# STAGES — on-device performance baseline capture for issue #119.
# Run from the repo root on the laptop the phone is plugged into:
#   bash tools/baseline/baseline_wizard.sh
# Produces docs/baseline-s26u.md (the table #119 asks for) and saves raw
# captures under tools/baseline/captures/. Re-runnable: captured values are
# remembered in tools/baseline/.baseline.env, so you can stop and resume.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
ENV_FILE="tools/baseline/.baseline.env"
PKG="com.spectrafilm.app"
CAP_DIR="tools/baseline/captures"
mkdir -p "$CAP_DIR"

# adbw: adb against the chosen device (set in stage 1).
ADB_SERIAL=""
adbw() { if [[ -n "$ADB_SERIAL" ]]; then adb -s "$ADB_SERIAL" "$@"; else adb "$@"; fi }

# spektra_log: everything the app's Spektra diagnostics tag logged since the
# last `adbw logcat -c`.
spektra_log() { adbw logcat -d -s Spektra 2>/dev/null; }

# last_export_ms: duration from the newest "export … ok in NNNms" breadcrumb.
last_export_ms() { spektra_log | grep -oE 'export format=[A-Z0-9_]+ ok in [0-9]+ms' | tail -n1 | grep -oE '[0-9]+ms$' | tr -d 'ms'; }

# preview_ms_list: every preview render duration since the last clear.
preview_ms_list() { spektra_log | grep -oE 'render mode=preview [0-9]+x[0-9]+ [0-9]+px [0-9]+ms' | grep -oE '[0-9]+ms$' | tr -d 'ms'; }

# median/max of a newline list of integers.
stat_median() { sort -n | awk '{a[NR]=$1} END {if (NR==0) {print "-"; exit} if (NR%2) print a[(NR+1)/2]; else print int((a[NR/2]+a[NR/2+1])/2)}'; }
stat_max()    { sort -n | tail -n1; }

# wait_export: poll the breadcrumbs until an export finishes (ok or failed).
wait_export() {
  say "Waiting for the export to finish (watching logcat)…"
  local t=0
  while (( t < 900 )); do
    if spektra_log | grep -qE 'export format=.* (ok in [0-9]+ms|failed)'; then return 0; fi
    sleep 2; t=$((t + 2))
  done
  warn "no export breadcrumb after 15 min — did the export run?"
  return 1
}

banner "Spektrafilm on-device baseline (#119)"

# ── Stage 1: preflight ────────────────────────────────────────────────────
stage "Preflight: laptop + phone"
say "Checks the tools and the phone connection, and records the device identity."
command -v adb >/dev/null 2>&1 || { warn "adb not found — install Android platform-tools first"; exit 1; }
[[ -f settings.gradle.kts ]] || { warn "run this from the Spektrafilm-android repo root"; exit 1; }
step "Plug in the phone, unlock it, and accept the USB-debugging prompt if shown."
pause
say "Devices adb can see:"
adb devices | sed 's/^/    /'
ask ADB_SERIAL "Device serial to use (Enter for the only/default device):"
DEVICE_MODEL=$(adbw shell getprop ro.product.model | tr -d '\r')
DEVICE_REL=$(adbw shell getprop ro.build.version.release | tr -d '\r')
DEVICE_ABI=$(adbw shell getprop ro.product.cpu.abi | tr -d '\r')
DEVICE_SOC=$(adbw shell getprop ro.soc.model 2>/dev/null | tr -d '\r')
say "Connected: ${DEVICE_MODEL} · Android ${DEVICE_REL} · ${DEVICE_ABI} · SoC ${DEVICE_SOC:-?}"
write_env ADB_SERIAL "$ADB_SERIAL"
write_env DEVICE_MODEL "$DEVICE_MODEL"
write_env DEVICE_REL "$DEVICE_REL"
write_env DEVICE_ABI "$DEVICE_ABI"
write_env DEVICE_SOC "$DEVICE_SOC"

# ── Stage 2: build + install the release APK ──────────────────────────────
stage "Build and install the release (R8) APK"
BASELINE_SHA=$(git rev-parse --short HEAD)
say "Baseline builds from the CURRENT checkout: $BASELINE_SHA"
note "Must include the #119 prep commit (export-timing breadcrumbs + <profileable>),"
note "or stages 5–7 have nothing to read. Without keystore.properties the release"
note "build falls back to debug signing — fine for a sideloaded baseline."
note "RELEASE, not debug, and this is not a formality: debug and release differ"
note "by ~2x overall and UNEVENLY per module (perf-lab.md 19). A baseline taken"
note "on a debug APK measures the compiler, not the app, and cannot be compared"
note "against any release number. Record the build type in every table."
if confirm "Run ./gradlew :app:assembleRelease now (few minutes)?"; then
  ./gradlew :app:assembleRelease
  APK=app/build/outputs/apk/release/app-release.apk
  [[ -f "$APK" ]] || APK=$(ls app/build/outputs/apk/release/*.apk 2>/dev/null | head -n1)
  say "Installing $APK…"
  adbw install -r "$APK"
else
  warn "Skipped the build — make sure the installed app already has the #119 breadcrumbs."
fi
INSTALLED_VER=$(adbw shell dumpsys package "$PKG" 2>/dev/null | grep -m1 versionName | tr -d '\r' | sed 's/^ *//')
say "Installed: ${INSTALLED_VER:-unknown}"
write_env BASELINE_SHA "$BASELINE_SHA"
write_env INSTALLED_VER "${INSTALLED_VER:-unknown}"

# ── Stage 3: import the test RAW ──────────────────────────────────────────
stage "Import the 12 MP test RAW"
step "Open Spektrafilm on the phone and import the RAW/DNG you'll baseline with"
step "(~12 MP; use the SAME file for every later stage and note it here)."
step "Wait until the preview has rendered once."
pause "Done importing?"
ask SCENE_NAME "Filename of the RAW (as you'll recognise it later):"
ask SCENE_MEGAPIXELS "Its resolution, e.g. 4000x3000 (check the file details):"
write_env SCENE_NAME "$SCENE_NAME"
write_env SCENE_MEGAPIXELS "$SCENE_MEGAPIXELS"

# ── Stage 4: preview slider-settle latency ────────────────────────────────
stage "Preview latency (640 px, scan + print routes)"
say "For each route: drag the Exposure slider ~5 separate times, letting the"
say "preview settle fully between drags. The wizard reads every preview render"
say "duration from the Spektra breadcrumbs and records the median and max."
for ROUTE in scan print; do
  printf '\n'
  if [[ "$ROUTE" == scan ]]; then
    step "Set the route to SCAN: Simulation > Scanner > 'Slide mode (skip print)' ON. Leave grain/halation at defaults."
  else
    step "Set the route to PRINT: Simulation > Scanner > 'Slide mode (skip print)' OFF."
  fi
  pause "Route set? Starting capture — press Enter, then do the 5 drags."
  adbw logcat -c
  pause "Done with ~5 drags on the $ROUTE route? (Enter)"
  LIST=$(preview_ms_list)
  COUNT=$(printf '%s\n' "$LIST" | grep -c . || true)
  MED=$(printf '%s\n' "$LIST" | stat_median)
  MAX=$(printf '%s\n' "$LIST" | stat_max)
  say "Captured $COUNT preview renders on $ROUTE: median ${MED} ms, max ${MAX:--} ms"
  if [[ "$ROUTE" == scan ]]; then
    write_env PREVIEW_SCAN_MED_MS "$MED"; write_env PREVIEW_SCAN_MAX_MS "${MAX:--}"
  else
    write_env PREVIEW_PRINT_MED_MS "$MED"; write_env PREVIEW_PRINT_MAX_MS "${MAX:--}"
  fi
done

# ── Stage 5: 12 MP export wall times (8 combos) ───────────────────────────
stage "Export wall times: grain × route × format"
say "Eight exports. For each combo the wizard tells you the toggles, you run"
say "Export in the app, and the duration is read from the breadcrumb."
note "Format lives in the export sheet (PNG 16-bit / TIFF). Grain: the Grain"
note "section's Active toggle. Route: Simulation > Scanner > 'Slide mode (skip print)'"
note "(ON = scan/slide, OFF = print)."
for COMBO in \
  "grainOFF scan PNG16" "grainOFF scan TIFF" \
  "grainOFF print PNG16" "grainOFF print TIFF" \
  "grainON scan PNG16"  "grainON scan TIFF" \
  "grainON print PNG16" "grainON print TIFF"; do
  set -- $COMBO
  GRAIN=$1; ROUTE=$2; FMT=$3
  KEY="EXPORT_${GRAIN}_${ROUTE}_${FMT}_MS"
  EXISTING=$(_existing "$KEY" || true)
  if [[ -n "$EXISTING" ]]; then
    say "✓ $GRAIN / $ROUTE / $FMT already captured (${EXISTING} ms) — skipping."
    continue
  fi
  printf '\n'
  step "Set: grain ${GRAIN#grain}, route $(printf '%s' "$ROUTE" | tr '[:lower:]' '[:upper:]'), then Export as ${FMT}."
  pause "Ready? Press Enter, THEN tap Export in the app."
  adbw logcat -c
  wait_export || continue
  MS=$(last_export_ms)
  if [[ -n "$MS" ]]; then
    say "→ ${MS} ms"
    write_env "$KEY" "$MS"
  else
    warn "export failed or breadcrumb missing — check the app, rerun this combo later"
  fi
done

# ── Stage 6: peak RSS during a grain-ON export ────────────────────────────
stage "Peak RSS (12 MP grain-ON print export)"
say "VmHWM is the kernel's high-water mark for the process, so we restart the"
say "app first to isolate one export."
step "Force-stop coming — after it, reopen Spektrafilm, re-import $SCENE_NAME,"
step "set grain ON + PRINT route, and run ONE PNG16 export."
pause "Ready for the force-stop?"
adbw shell am force-stop "$PKG"
pause "App reopened, image imported, export DONE? (Enter)"
PID=$(adbw shell pidof "$PKG" | tr -d '\r')
if [[ -n "$PID" ]]; then
  VMHWM=$(adbw shell cat "/proc/$PID/status" 2>/dev/null | grep VmHWM | grep -oE '[0-9]+' || true)
  if [[ -n "$VMHWM" ]]; then
    say "VmHWM: ${VMHWM} kB (~$(( VMHWM / 1024 )) MB)"
    write_env RSS_PEAK_KB "$VMHWM"
  else
    warn "/proc not readable on this build — falling back to a one-shot PSS reading"
    PSS=$(adbw shell dumpsys meminfo "$PKG" 2>/dev/null | grep -m1 "TOTAL PSS" | grep -oE '[0-9]+' | head -n1 || true)
    say "TOTAL PSS now: ${PSS:-?} kB (post-export, NOT the true peak — note it as such)"
    write_env RSS_PEAK_KB "${PSS:-unknown}"
  fi
else
  warn "app process not found — rerun this stage"
fi

# ── Stage 7: simpleperf flamegraph of a grain-ON export ───────────────────
stage "simpleperf profile (grain-ON export)"
say "The <profileable android:shell> flag in this build lets shell simpleperf"
say "attach to the release app. We record 90 s covering one grain-ON export."
step "In the app: grain ON, PRINT route, export sheet open and ready on PNG16."
pause "Ready? Press Enter to START recording, then IMMEDIATELY tap Export."
PID=$(adbw shell pidof "$PKG" | tr -d '\r')
if [[ -z "$PID" ]]; then warn "app not running — open it and rerun this stage"; else
  adbw shell "cd /data/local/tmp && simpleperf record -p $PID --duration 90 -g -e cpu-clock -o /data/local/tmp/spk-baseline.perf.data" || warn "simpleperf record failed"
  say "Pulling the capture…"
  adbw pull /data/local/tmp/spk-baseline.perf.data "$CAP_DIR/spk-baseline.perf.data" && \
    say "→ $CAP_DIR/spk-baseline.perf.data"
  note "Report later with the NDK's simpleperf scripts, using the UNSTRIPPED libs:"
  note "  python \$NDK/simpleperf/report_html.py -i $CAP_DIR/spk-baseline.perf.data \\"
  note "    --binary_filter libspektra.so -o $CAP_DIR/spk-baseline-report.html"
  note "  (unstripped .so: app/build/intermediates/merged_native_libs/release/out/lib/arm64-v8a/)"
  write_env PERF_DATA "$CAP_DIR/spk-baseline.perf.data"
fi

# ── Stage 8: write the baseline table ─────────────────────────────────────
stage "Write docs/baseline-s26u.md"
OUT=docs/baseline-s26u.md
g() { _existing "$1" || printf '%s' "-"; }
say "About to write $OUT from everything captured."
if confirm "Write it now?"; then
  {
    printf '# On-device performance baseline — %s (#119)\n\n' "$(g DEVICE_MODEL)"
    printf 'Captured %s · device %s · Android %s · %s · SoC %s\n' "$(date +%F)" "$(g DEVICE_MODEL)" "$(g DEVICE_REL)" "$(g DEVICE_ABI)" "$(g DEVICE_SOC)"
    printf 'App %s · release/R8 build of `%s` · scene `%s` (%s)\n\n' "$(g INSTALLED_VER)" "$(g BASELINE_SHA)" "$(g SCENE_NAME)" "$(g SCENE_MEGAPIXELS)"
    printf '## 12 MP export wall time (ms)\n\n'
    printf '| grain | route | PNG16 | TIFF |\n|---|---|---:|---:|\n'
    printf '| OFF | scan | %s | %s |\n' "$(g EXPORT_grainOFF_scan_PNG16_MS)" "$(g EXPORT_grainOFF_scan_TIFF_MS)"
    printf '| OFF | print | %s | %s |\n' "$(g EXPORT_grainOFF_print_PNG16_MS)" "$(g EXPORT_grainOFF_print_TIFF_MS)"
    printf '| ON | scan | %s | %s |\n' "$(g EXPORT_grainON_scan_PNG16_MS)" "$(g EXPORT_grainON_scan_TIFF_MS)"
    printf '| ON | print | %s | %s |\n\n' "$(g EXPORT_grainON_print_PNG16_MS)" "$(g EXPORT_grainON_print_TIFF_MS)"
    printf '## Interactive preview (640 px, per-render ms over ~5 slider drags)\n\n'
    printf '| route | median | max |\n|---|---:|---:|\n'
    printf '| scan | %s | %s |\n' "$(g PREVIEW_SCAN_MED_MS)" "$(g PREVIEW_SCAN_MAX_MS)"
    printf '| print | %s | %s |\n\n' "$(g PREVIEW_PRINT_MED_MS)" "$(g PREVIEW_PRINT_MAX_MS)"
    printf '## Peak RSS, 12 MP grain-ON print export\n\nVmHWM: %s kB\n\n' "$(g RSS_PEAK_KB)"
    printf '## simpleperf capture\n\n`%s` (report per tools/baseline/README.md)\n\n' "$(g PERF_DATA)"
    printf '*Captured with tools/baseline/baseline_wizard.sh. Film modeling powered by spektrafilm (GPLv3).*\n'
  } > "$OUT"
  say "✓ wrote $OUT"
  note "Next: review it, then commit + push, and paste the tables into issue #119:"
  note "  git add $OUT && git commit -m 'docs: on-device baseline (#119)' && git push"
else
  warn "Skipped writing $OUT — rerun this stage when ready."
fi

finish
